### PR TITLE
Check `post.categories` instead of `post.category`

### LINKED ISSUE #356: Custom feed for categories doesn't work if it contains åäö
I just tried adding custom feeds for a few catergories to one of my websites. One of this categories is "Träffar" (Meetups).

It does generate a feed, but it doesn't contain any posts.

I'm running Jekyll 4.2.1 with jekyll-feed 0.15.1.

### PR DESCRIPTION
**Pull request by ashmaroli**
Since `Jekyll::Document#data["categories"]` is generated from `doc.data["category"]`.
Closes #356

### CODE REVIEW

File: spec/jekyll-feed_spec.rb [hunk 1]
```diff
@@ -411,11 +411,9 @@ def to_s
...
 
       it "outputs the category feed" do
-        expect(news_feed).to match '<title type="html">My awesome site | News</title>'
-        expect(news_feed).to match "http://example.org/news/2014/03/02/march-the-second.html"
-        expect(news_feed).to match "http://example.org/news/2013/12/12/dec-the-second.html"
-        expect(news_feed).to_not match "http://example.org/updates/jekyll/2014/03/04/march-the-fourth.html"
-        expect(news_feed).to_not match "http://example.org/2015/08/08/stuck-in-the-middle.html"
+        expect(category_feed).to match '<title type="html">My awesome site | News</title>'
+        expect(category_feed).to match "http://example.org/updates/jekyll/2014/03/04/march-the-fourth.html"
+        expect(category_feed).to match "March the fourth!"
```
Comment (parkr) [inline spec/jekyll-feed_spec.rb:416]: Could we cover the `category: jekyll` case too? The fixtures don't seem to have a post with the singular key name

**Review by parkr — APPROVED** [review]
Implementation is fine! Would love to add a test to ensure singular key is tested.

File: spec/jekyll-feed_spec.rb (hunk 1 above)
Comment (ashmaroli) [reply spec/jekyll-feed_spec.rb]: > The fixtures don't seem to have a post with the singular key name

The existing test on `master` uses a fixture post with a singular key name..

**Review by parkr — APPROVED** [review]

**Comment by parkr** [comment]
@jekyllbot: merge +fix
